### ISSUE TITLE
Hand Gestures with Smartphone for Cropping Tool

### ISSUE THREAD

**Issue by fauzikitalabs** [brainhubeu/react-file-input#79]
Hello,

Hope you find this question well.

I am really excited with this project. It already helps us a lot in terms of image upload management. 

Just would like to understand more about this project. Does the cropping tool support the hand gesture for smartphone user?

Regards,

Fauzi

**Comment by piotr-s-brainhub** [comment]
@fauzikitalabs 

Thanks for this question. I see cropping doesn't work properly in https://brainhubeu.github.io/react-file-input/docs/examples/cropTool because it just uploads an image and I'm not able to crop it. However, I will consult that with my team.

**Comment by fauzikitalabs** [comment]
No problem at all. I do wish some improvements for this project because it helped simplifying the image upload process. Wish you and your team a really good luck for this. ;)

**Comment by piotr-s-brainhub** [comment]
@fauzikitalabs 

I created:
- [mobile - I cannot crop as I'd like to](https://github.com/brainhubeu/react-file-input/issues/80)
- [mobile - no image preview](https://github.com/brainhubeu/react-file-input/issues/81)

**Comment by piotr-s-brainhub** [comment]
So the cropping works on desktop but only partially on mobile (hand gestures aren't available).
